CREATE OR REPLACE WAREHOUSE WH_18;
USE WAREHOUSE WH_18;

CREATE OR REPLACE DATABASE CLEANROOM_SHARED_DB;
USE DATABASE CLEANROOM_SHARED_DB;

CREATE OR REPLACE SCHEMA PARTNER_TELEMETRY;
USE SCHEMA PARTNER_TELEMETRY;

CREATE OR REPLACE FILE FORMAT FILE_FORMAT_18
TYPE = JSON;

CREATE OR REPLACE STAGE STAGE18
FILE_FORMAT = FILE_FORMAT_18;

LIST @STAGE18;

CREATE OR REPLACE TABLE BRONZE_RETAIL_TRANSACTIONS
(
PAYLOAD1 VARIANT
);

CREATE OR REPLACE TABLE BRONZE_AD_EXPOSURES
(
PAYLOAD2 VARIANT
);

COPY INTO BRONZE_RETAIL_TRANSACTIONS
FROM @stage18/retail_transactions18.json;

COPY INTO BRONZE_AD_EXPOSURES
FROM @stage18/ad_exposures18.json;

SELECT * FROM BRONZE_RETAIL_TRANSACTIONS;
SELECT * FROM BRONZE_AD_EXPOSURES;

CREATE OR REPLACE TABLE SILVER_ATTRIBUTION_MATCH
(
    POS_ID STRING,
    STORE_ID STRING,
    CAMPAIGN_NAME STRING,
    CHANNEL STRING,
    BASKET_VALUE NUMBER(10,2),
    CONVERSION_HOURS NUMBER
);

SELECT * FROM SILVER_ATTRIBUTION_MATCH;

INSERT INTO SILVER_ATTRIBUTION_MATCH
(
POS_ID,
STORE_ID,
CAMPAIGN_NAME,
CHANNEL,
BASKET_VALUE,
CONVERSION_HOURS
)
SELECT r.payload1:pos_id::string,
       r.payload1:store_id::STRING,
       a.PAYLOAD2:campaign_name::STRING,
       a.payload2:channel::STRING,
       r.payload1:basket_value::NUMBER(10,2),
       DATEDIFF('hour', a.payload2:timestamp::TIMESTAMP,r.payload1:timestamp::TIMESTAMP)
FROM BRONZE_RETAIL_TRANSACTIONS r
JOIN BRONZE_AD_EXPOSURES a
on r.payload1:hashed_email::STRING = a.payload2:hashed_email::STRING;

SELECT * FROM SILVER_ATTRIBUTION_MATCH;

CREATE OR REPLACE SECURE VIEW SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE AS
SELECT CAMPAIGN_NAME,
       COUNT(POS_ID) CONVERTED_USER_COUNT,
       SUM(BASKET_VALUE) TOTAL_ATTRIBUTED_VAL,
       ROUND(AVG(BASKET_VALUE),2) AVG_BASKET_VALUE
FROM SILVER_ATTRIBUTION_MATCH
GROUP BY CAMPAIGN_NAME;

SELECT * FROM SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE;

/* TASK 4 */

CREATE OR REPLACE SHARE SHARE_CPG_PARTNER_ANALYTICS;

GRANT USAGE
ON DATABASE CLEANROOM_SHARED_DB
TO SHARE SHARE_CPG_PARTNER_ANALYTICS;

GRANT USAGE 
ON SCHEMA PARTNER_TELEMETRY
TO SHARE SHARE_CPG_PARTNER_ANALYTICS;

GRANT SELECT
ON VIEW SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE
TO SHARE SHARE_CPG_PARTNER_ANALYTICS;

ALTER SHARE SHARE_CPG_PARTNER_ANALYTICS
ADD ACCOUNTS = CPG_PARTNER_ACCT;

SHOW SHARES  LIKE 'SHARE_CPG_PARTNER_ANALYTICS';


SELECT
    "name" AS NAME,
    "database_name" AS DATABASE_NAME,
    "to" AS RECIPENT,
    "kind" = 'OUTBOUND' AS IS_OUTBOUND
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

/* TASK 5 READER ACCOUNT WHEN THE OTHER PERSON DOESNT HAVE SNOWFALKE ACCOUNT */

CREATE MANAGED ACCOUNT CPG_READER_ACCT_01
ADMIN_NAME = CPG_ADMIN
ADMIN_PASSWORD = 'StrongPassword@123'
TYPE = READER;

ALTER SHARE SHARE_CPG_PARTNER_ANALYTICS
ADD ACCOUNTS = YA32767;

SHOW MANAGED ACCOUNTS;

SELECT "account_name",
        "cloud",
        "region",
        CASE WHEN "is_reader" = True 
             THEN 'READER'
             ELSE  'NOT READER'
        END AS ACCOUNT_TYPE
from TABLE(RESULT_SCAN(LAST_QUERY_ID()));

/* TASK 6 */

SELECT
    (SELECT SUM(BASKET_VALUE)
     FROM SILVER_ATTRIBUTION_MATCH) AS SILVER_MATCH_VAL,

    (SELECT SUM(TOTAL_ATTRIBUTED_VAL)
     FROM SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE) AS GOLD_SHARED_VAL,

    FALSE AS PII_EXPOSURE_FLAG,

    (
      (SELECT SUM(BASKET_VALUE)
       FROM SILVER_ATTRIBUTION_MATCH)
      =
      (SELECT SUM(TOTAL_ATTRIBUTED_VAL)
       FROM SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE)
    ) AS RECONCILED_FLAG;





