CREATE WAREHOUSE IF NOT EXISTS CUSTOMER_HISTORY_WH9;
USE WAREHOUSE CUSTOMER_HISTORY_WH9;

CREATE DATABASE IF NOT EXISTS CUSTOMER_HISTORY_DB9;
USE DATABASE CUSTOMER_HISTORY_DB9;

CREATE SCHEMA IF NOT EXISTS SCD_TYPE2_MODEL9;
USE SCHEMA SCD_TYPE2_MODEL9;

CREATE FILE FORMAT IF NOT EXISTS FILE_FORMAT_9
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE STAGE IF NOT EXISTS STAGE9
FILE_FORMAT = FILE_FORMAT_9;


/* -- scd type 1 -- */

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE1 (
    CUSTOMER_KEY INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(30),
    CITY VARCHAR(20),
    STATE VARCHAR(20),
    MEMBERSHIP VARCHAR(20),
    SEGMENT VARCHAR(20)
);

COPY INTO DIM_CUSTOMER_TYPE1
(   CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE ,
    MEMBERSHIP ,
    SEGMENT)
FROM @stage9/customers_initial9.csv;

SELECT * FROM DIM_CUSTOMER_TYPE1;

CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(30),
    CITY VARCHAR(20),
    STATE VARCHAR(20),
    MEMBERSHIP VARCHAR(20),
    SEGMENT VARCHAR(20),
    EFFECTIVE_DATE DATE
);


LIST @STAGE9;

COPY INTO CUSTOMER_UPDATES
FROM @stage9/customer_updates9.csv;

select * from dim_customer_type1
order by customer_id;

select * from customer_updates;

update dim_customer_type1 d
set city = c.city,
    state = c.state,
    membership = c.membership,
    segment = c.segment
from customer_updates c
where d.customer_id = c.customer_id;

/* --- scd type 2 --- */

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE2 (
    CUSTOMER_KEY INT AUTOINCREMENT START 1 INCREMENT 1 ORDER PRIMARY KEY,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(30),
    CITY VARCHAR(20),
    STATE VARCHAR(20),
    MEMBERSHIP VARCHAR(20),
    SEGMENT VARCHAR(20),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);


COPY INTO DIM_CUSTOMER_TYPE2
(CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT)
FROM @STAGE9/customers_initial9.csv;

select * from DIM_CUSTOMER_TYPE2;

update DIM_CUSTOMER_TYPE2
set EFFECTIVE_DATE = '2026-01-01',
    expiry_date = '9999-12-31',
    is_current = True;

/* -- EXPIRE THE OLD ROW -- */

UPDATE DIM_CUSTOMER_TYPE2 d
set EXPIRY_DATE = DATEADD(DAY,-1,u.effective_date),
    is_current = FALSE
from customer_updates u
where d.customer_id = u.customer_id and d.is_current = TRUE;

/* --- Insert new row --- */

INSERT INTO DIM_CUSTOMER_TYPE2
(   CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT)
    
SELECT  CUSTOMER_ID,
        CUSTOMER_NAME,
        CITY,
        STATE,
        MEMBERSHIP,
        SEGMENT,
        EFFECTIVE_DATE,
        '9999-12-31',
        TRUE
FROM CUSTOMER_UPDATES;

SELECT * FROM DIM_CUSTOMER_TYPE2
where CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;