CREATE OR REPLACE WAREHOUSE WH_16;
USE WAREHOUSE WH_16;

CREATE OR REPLACE DATABASE HEALTHCARE_PIPELINE_DB;
USE DATABASE HEALTHCARE_PIPELINE_DB;

CREATE OR REPLACE  SCHEMA CLAIMS_CORE;
USE SCHEMA CLAIMS_CORE;

CREATE OR REPLACE FILE FORMAT FILE_FORMAT_16
TYPE = JSON;

CREATE OR REPLACE STAGE STAGE16
FILE_FORMAT = FILE_FORMAT_16;

LIST @STAGE16;

/* task 1  bronze layer*/

CREATE OR REPLACE TABLE BRONZE_RAW_CLAIMS
(
INGEST_ID INT AUTOINCREMENT START 1 INCREMENT 1 ORDER PRIMARY KEY,
PAYLOAD VARIANT,
LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

/* creating stream on bronze */

CREATE OR REPLACE STREAM STREAM_BRONZE_CLAIMS
ON TABLE BRONZE_RAW_CLAIMS;

select * from stream_bronze_claims;

SELECT * FROM BRONZE_RAW_CLAIMS;


COPY INTO BRONZE_RAW_CLAIMS(PAYLOAD)
FROM @stage16/batch1_claims_stream16.json
ON_ERROR = CONTINUE;

create or replace file format format16
type = 'csv',
field_delimiter = NONE;

/* task 2 error handling storing errors */


create or replace  table QUARANTINE_CLAIMS_PAYLOADS
(
QUARANTINE_ID INT AUTOINCREMENT START 1 INCREMENT 1 ORDER PRIMARY KEY,
RAW_RECORD_TEXT VARCHAR(1000),
REASON VARCHAR(200)
);

insert into QUARANTINE_CLAIMS_PAYLOADS(RAW_RECORD_TEXT,REASON)
select $1,
       'MALFORMED_JSON_BODY'
from @stage16
(file_format => format16)
where try_parse_json($1) is null;

/* creating silver */

CREATE OR REPLACE TABLE SILVER_CLAIMS_TRANSACTIONS
(
    CLAIM_ID STRING,
    SUBMITTED_AT TIMESTAMP,
    PATIENT_ID NUMBER,
    PROVIDER_ID STRING,
    DIAGNOSIS_CODE STRING,
    BILLED_AMOUNT NUMBER(12,2),
    COPAY_AMOUNT NUMBER(12,2),
    NET_PAYABLE_AMOUNT NUMBER(12,2),
    STATUS STRING
);

SELECT * FROM SILVER_CLAIMS_TRANSACTIONS;

/* MERGING INTO SILVER USING STREAM */

MERGE INTO SILVER_CLAIMS_TRANSACTIONS s
USING stream_bronze_claims st
ON s.claim_id = st.PAYLOAD:claim_id::STRING

WHEN MATCHED THEN
UPDATE
SET
    PATIENT_ID = st.PAYLOAD:patient_id::NUMBER,
    SUBMITTED_AT = st.PAYLOAD:submitted_at::TIMESTAMP,
    PROVIDER_ID = st.PAYLOAD:provider_id::STRING,
    DIAGNOSIS_CODE = st.PAYLOAD:diagnosis_code::STRING,
    BILLED_AMOUNT = st.PAYLOAD:billed_amount::NUMBER(12,2),
    COPAY_AMOUNT = st.PAYLOAD:copay_amount::NUMBER(12,2),
    NET_PAYABLE_AMOUNT =
        st.PAYLOAD:billed_amount::NUMBER(12,2)
        - st.PAYLOAD:copay_amount::NUMBER(12,2),
    STATUS = st.PAYLOAD:status::STRING

WHEN NOT MATCHED THEN

INSERT
(
    CLAIM_ID,
    SUBMITTED_AT,
    PATIENT_ID,
    PROVIDER_ID,
    DIAGNOSIS_CODE,
    BILLED_AMOUNT,
    COPAY_AMOUNT,
    NET_PAYABLE_AMOUNT,
    STATUS
)
values(
    st.PAYLOAD:claim_id::STRING,
    st.PAYLOAD:submitted_at::TIMESTAMP,
    st.PAYLOAD:patient_id::NUMBER,
    st.PAYLOAD:provider_id::STRING,
    st.PAYLOAD:diagnosis_code::STRING,
    st.PAYLOAD:billed_amount::NUMBER(12,2),
    st.PAYLOAD:copay_amount::NUMBER(12,2),
    st.PAYLOAD:billed_amount::NUMBER(12,2) -
        st.PAYLOAD:copay_amount::NUMBER(12,2),
    st.PAYLOAD:status::STRING
);

CREATE OR REPLACE DYNAMIC TABLE DT_PROVIDER_FINANCIAL_SUMMARY
TARGET_LAG = '1 MINUTE'
WAREHOUSE = WH_16
AS 
SELECT PROVIDER_ID,
       sum(billed_amount) AS TOTAL_BILLED_AMOUNT,
       sum(COPAY_AMOUNT) AS TOTAL_COPAY_COLLECT,
       sum(net_payable_amount) AS TOTAL_NET_PAYABLE,
       count(*) AS APPROVED_CLAIMS
FROM SILVER_CLAIMS_TRANSACTIONS
where status = 'APPROVED'
group by PROVIDER_ID;

SELECT * FROM DT_PROVIDER_FINANCIAL_SUMMARY;

/* LOADING BATCH 2 */

COPY INTO BRONZE_RAW_CLAIMS(PAYLOAD)
FROM @stage16/batch2_claims_stream16.json
ON_ERROR = CONTINUE;

SELECT * FROM BRONZE_RAW_CLAIMS;

SELECT * FROM STREAM_BRONZE_CLAIMS;

/* RUN THE MERGE QUERY ONCE TO SEE THE UPDATE */

/* after running query rows inserted 1 rows updated 2 */

select * from silver_claims_transactions;

ALTER DYNAMIC TABLE DT_PROVIDER_FINANCIAL_SUMMARY REFRESH;/* refreshes on point */

select * from dt_provider_financial_summary;

/* loading batch 3 */

list @stage16;

copy into bronze_raw_claims(payload)
from @stage16/batch3_claims_stream16.json
on_error = CONTINUE;

SELECT * FROM BRONZE_RAW_CLAIMS;


/* BATCH 3 LOADED NOW RUN MERGE ONCE AGAIN */

/* after running merge rows inserted 1 rows updated 0 */

select * from silver_claims_transactions;

ALTER DYNAMIC TABLE DT_PROVIDER_FINANCIAL_SUMMARY REFRESH; /* refreshes on point */

SELECT * FROM DT_PROVIDER_FINANCIAL_SUMMARY
ORDER BY PROVIDER_ID;

/* AFTER SUCESSFULLY LOADING ALL THE BATCHES 
FOR EVERY BATCH LOAD STREAM CHANGES,
SO WE HAVE TO RUN  MERGE WITH STREAM FOR SILVER ,
THE SILVER TABLE WILL UPDATE ACCORDINGLY ,
THEN DYNAMIC TABLE WILL REFRESH AFTER 1 MINUTE AUTOMATICALLY USING SILVER TO GET THE LATEST INFO */

/* task 5 */
SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY()
)
WHERE NAME = 'DT_PROVIDER_FINANCIAL_SUMMARY'
ORDER BY DATA_TIMESTAMP DESC;

/* task 6 */
SELECT
    b.BRONZE_GROSS_TOTAL,
    s.SILVER_GROSS_TOTAL,
    g.GOLD_GROSS_TOTAL,
    (s.SILVER_GROSS_TOTAL = 197700
     AND g.GOLD_GROSS_TOTAL = 152700) AS RECONCILED_FLAG
FROM
(
    SELECT SUM(PAYLOAD:billed_amount::NUMBER(12,2)) AS BRONZE_GROSS_TOTAL
    FROM BRONZE_RAW_CLAIMS /* all 8 rows sum */
) b
CROSS JOIN
(
    SELECT SUM(BILLED_AMOUNT) AS SILVER_GROSS_TOTAL
    FROM SILVER_CLAIMS_TRANSACTIONS /* non duplicate sum */
) s
CROSS JOIN
(
    SELECT SUM(TOTAL_BILLED_AMOUNT) AS GOLD_GROSS_TOTAL
    FROM DT_PROVIDER_FINANCIAL_SUMMARY /* only approved sum */
) g;







