CREATE WAREHOUSE IF NOT EXISTS CUSTOMER_HISTORY_WH10;
USE WAREHOUSE CUSTOMER_HISTORY_WH10;

CREATE DATABASE IF NOT EXISTS CUSTOMER_HISTORY_DB10;
USE DATABASE CUSTOMER_HISTORY_DB10;

CREATE SCHEMA IF NOT EXISTS SCD_TYPE3_TYPE6_MODEL10;
USE SCHEMA SCD_TYPE3_TYPE6_MODEL10;

CREATE FILE FORMAT IF NOT EXISTS FILE_FORMAT_10
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE STAGE IF NOT EXISTS STAGE10
FILE_FORMAT = FILE_FORMAT_10;

LIST @STAGE10;

/* --- SCD TYPE 3 --- */

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE3(
    CUSTOMER_KEY INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(30),
    CITY VARCHAR(20),
    STATE VARCHAR(20),
    CURRENT_MEMBERSHIP VARCHAR(20),
    PREVIOUS_MEMBERSHIP VARCHAR(20),
    SEGMENT VARCHAR(20)
);

COPY INTO DIM_CUSTOMER_TYPE3
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    SEGMENT
)
FROM @STAGE10/customers_initial10.csv;


CREATE OR REPLACE TABLE CUSTOMER_UPDATES10 (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(30),
    CITY VARCHAR(20),
    STATE VARCHAR(20),
    MEMBERSHIP VARCHAR(20),
    SEGMENT VARCHAR(20),
    EFFECTIVE_DATE DATE
);

COPY INTO CUSTOMER_UPDATES10
FROM @STAGE10/customer_updates10.csv;

SELECT * FROM CUSTOMER_UPDATES10;
SELECT * FROM DIM_CUSTOMER_TYPE3
order by customer_id;

UPDATE DIM_CUSTOMER_TYPE3 t
SET previous_membership = t.CURRENT_MEMBERSHIP,
    CURRENT_MEMBERSHIP = u.MEMBERSHIP
FROM CUSTOMER_UPDATES10 u
where t.CUSTOMER_ID = u.customer_id;

/* --- SCD TYPE 6 --- */

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE6 (
    CUSTOMER_KEY INT AUTOINCREMENT START 1 INCREMENT 1 ORDER PRIMARY KEY,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(30),
    CITY VARCHAR(20),
    STATE VARCHAR(20),
    CURRENT_MEMBERSHIP VARCHAR(20),
    PREVIOUS_MEMBERSHIP VARCHAR(20),
    HISTORICAL_MEMBERSHIP VARCHAR(20),
    SEGMENT VARCHAR(20),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

COPY INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    SEGMENT
)
FROM @STAGE10/customers_initial10.csv;

SELECT * FROM DIM_CUSTOMER_TYPE6;

UPDATE DIM_CUSTOMER_TYPE6
SET EFFECTIVE_DATE = '2026-01-01',
    EXPIRY_DATE = '9999-12-31',
    IS_CURRENT = TRUE;

update DIM_CUSTOMER_TYPE6 c
set historical_membership  = u.current_membership
from DIM_CUSTOMER_TYPE6 u
where c.customer_id = u.customer_id;

/* --- Update the current and expiry date --- */

update DIM_CUSTOMER_TYPE6 c
set expiry_date = dateadd(day,-1,u.effective_date),
    is_current = false
from customer_updates10 u
where c.customer_id = u.customer_id;

/* --- insert new rows --- */

insert into DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME ,
    CITY ,
    STATE ,
    CURRENT_MEMBERSHIP ,
    PREVIOUS_MEMBERSHIP ,
    HISTORICAL_MEMBERSHIP ,
    SEGMENT,
    EFFECTIVE_DATE ,
    EXPIRY_DATE ,
    IS_CURRENT )

select u.CUSTOMER_ID,
    u.CUSTOMER_NAME ,
    u.CITY ,
    u.STATE ,
    u.MEMBERSHIP ,
    d.current_membership,
    d.current_membership,
    u.SEGMENT,
    u.EFFECTIVE_DATE ,
    '9999-12-31',
    TRUE
from customer_updates10 u
JOIN DIM_CUSTOMER_TYPE6 d
on u.customer_id = d.customer_id
where d.is_current = false;

select * from DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID;