CREATE OR REPLACE WAREHOUSE WH_17;
USE WAREHOUSE WH_17;

CREATE OR REPLACE DATABASE FINANCIAL_GOVERNANCE_DB;
USE DATABASE FINANCIAL_GOVERNANCE_DB;

CREATE OR REPLACE SCHEMA WEALTH_CORE;
USE SCHEMA WEALTH_CORE;

CREATE OR REPLACE FILE FORMAT FILE_FORMAT_17
TYPE = JSON;

CREATE OR REPLACE FILE FORMAT FORMAT17
TYPE = CSV
FIELD_DELIMITER = NONE;

CREATE OR REPLACE STAGE STAGE17
FILE_FORMAT = FILE_FORMAT_17;

list @stage17;

/* task 1 */

CREATE OR REPLACE TABLE BRONZE_BANK_PAYLOADS
(
INGEST_ID INT AUTOINCREMENT START 1 INCREMENT 1 ORDER PRIMARY KEY,
PAYLOAD VARIANT,
LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
SELECT * FROM BRONZE_BANK_PAYLOADS;

COPY INTO BRONZE_BANK_PAYLOADS (PAYLOAD)
FROM @STAGE17
FILES = (
'batch1_banking_stream17.json',
'batch2_banking_stream17.json',
'batch3_banking_stream17.json'
)
ON_ERROR = CONTINUE;

SELECT * FROM BRONZE_BANK_PAYLOADS;

/* task 2 silver */

CREATE OR REPLACE TABLE SILVER_BANK_TRANSACTIONS
(
    TXN_ID STRING,
    CLIENT_ID NUMBER,
    CLIENT_SSN STRING,
    REGION STRING,
    ACCOUNT_NO STRING,
    AMOUNT NUMBER(15,2),
    STATUS STRING,
    AML_RISK_SCORE STRING
);

SELECT * FROM SILVER_BANK_TRANSACTIONS;

INSERT INTO SILVER_BANK_TRANSACTIONS
(
TXN_ID,
CLIENT_ID,
CLIENT_SSN,
REGION,
ACCOUNT_NO,
AMOUNT,
STATUS,
AML_RISK_SCORE
)
SELECT PAYLOAD:txn_id::STRING,
       PAYLOAD:client_id::NUMBER,
       PAYLOAD:client_ssn::STRING,
       PAYLOAD:region::STRING,
       PAYLOAD:account_no::STRING,
       PAYLOAD:amount::NUMBER(15,2),
       PAYLOAD:status::STRING,
       PAYLOAD:aml_risk_score::STRING
FROM BRONZE_BANK_PAYLOADS
ORDER BY PAYLOAD:client_id::NUMBER;

/* Role Based Access Control (RBAC)   */


CREATE OR REPLACE ROLE COMPLIANCE_OFFICER;
CREATE OR REPLACE ROLE NA_ANALYST;
CREATE OR REPLACE ROLE EU_ANALYST;

GRANT SELECT ON TABLE SILVER_BANK_TRANSACTIONS TO ROLE COMPLIANCE_OFFICER;
GRANT SELECT ON TABLE SILVER_BANK_TRANSACTIONS TO ROLE NA_ANALYST;
GRANT SELECT ON TABLE SILVER_BANK_TRANSACTIONS TO ROLE EU_ANALYST;

GRANT ROLE NA_ANALYST TO USER GCHARAN9999;
GRANT ROLE EU_ANALYST TO USER GCHARAN9999;
GRANT ROLE COMPLIANCE_OFFICER TO USER GCHARAN9999;

USE ROLE ACCOUNTADMIN;

/* TASK 3  Dynamic Data Masking (DDM)  */ 

CREATE OR REPLACE MASKING POLICY MASK_SSN
AS (CLIENT_SSN STRING)
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'COMPLIANCE_OFFICER')
    THEN CLIENT_SSN
    ELSE CONCAT('***-**-', RIGHT(CLIENT_SSN, 4))
END;

ALTER TABLE SILVER_BANK_TRANSACTIONS
MODIFY COLUMN CLIENT_SSN
SET MASKING POLICY MASK_SSN;

USE ROLE NA_ANALYST;
SELECT TXN_ID, CLIENT_SSN,ACCOUNT_NO
FROM SILVER_BANK_TRANSACTIONS;


CREATE OR REPLACE MASKING POLICY MASK_ACCOUNT
AS (ACCOUNT_NO STRING)
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'COMPLIANCE_OFFICER')
    THEN ACCOUNT_NO
    ELSE 'ACT-****'
END;

ALTER TABLE SILVER_BANK_TRANSACTIONS
MODIFY COLUMN ACCOUNT_NO
SET MASKING POLICY MASK_ACCOUNT;

USE ROLE NA_ANALYST;
SELECT TXN_ID, CLIENT_SSN,ACCOUNT_NO
FROM SILVER_BANK_TRANSACTIONS;


USE ROLE COMPLIANCE_OFFICER;
SELECT TXN_ID, CLIENT_SSN,ACCOUNT_NO
FROM SILVER_BANK_TRANSACTIONS;

USE ROLE NA_ANALYST;
SELECT TXN_ID, CLIENT_SSN,ACCOUNT_NO
FROM SILVER_BANK_TRANSACTIONS;

USE ROLE ACCOUNTADMIN;

/*  4 ROW ACCESS POLICY */


CREATE OR REPLACE ROW ACCESS POLICY RAP_REGION_POLICY
AS (REGION STRING)
RETURNS BOOLEAN ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','COMPLIANCE_OFFICER') THEN TRUE
    WHEN CURRENT_ROLE() = 'NA_ANALYST' AND REGION = 'NA' THEN TRUE
    WHEN CURRENT_ROLE() = 'EU_ANALYST' AND REGION = 'EU' THEN TRUE
    ELSE FALSE
END;

ALTER TABLE SILVER_BANK_TRANSACTIONS
ADD ROW ACCESS POLICY RAP_REGION_POLICY
ON (REGION);



USE ROLE NA_ANALYST;
USE ROLE EU_ANALYST;
USE ROLE COMPLIANCE_OFFICER;
USE ROLE ACCOUNTADMIN;

SELECT TXN_ID, REGION, CLIENT_SSN, ACCOUNT_NO
FROM SILVER_BANK_TRANSACTIONS;

SELECT * FROM SILVER_BANK_TRANSACTIONS;

/* TASK 5 GOLD */

CREATE OR REPLACE SECURE VIEW SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY
AS
SELECT REGION,
       SUM(amount) TOTAL_SETTLED_VAL,
       count(*) SETTLED_TXN_COUNT,
       ROUND(avg(amount),2) AVG_SETTLED_AMOUNT
from silver_bank_transactions
where status = 'SETTLED'
GROUP BY REGION;

SELECT * FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY;

SELECT
    B.BRONZE_GROSS_TOTAL,
    S.SILVER_GROSS_TOTAL,
    G.GOLD_GROSS_TOTAL,
    (B.BRONZE_GROSS_TOTAL = S.SILVER_GROSS_TOTAL) AS RECONCILED_FLAG
FROM
(
    SELECT SUM(PAYLOAD:amount::NUMBER(15,2)) AS BRONZE_GROSS_TOTAL
    FROM BRONZE_BANK_PAYLOADS
) B
CROSS JOIN
(
    SELECT SUM(AMOUNT) AS SILVER_GROSS_TOTAL
    FROM SILVER_BANK_TRANSACTIONS
) S
CROSS JOIN
(
    SELECT SUM(TOTAL_SETTLED_VAL) AS GOLD_GROSS_TOTAL
    FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY
) G;












       
